#!/bin/bash
set -euo pipefail

ART=/artifacts/arcturus
cd /app
# camera/ is the ./data/camera bind mount shared with nitro's nginx — the
# thumbnail subdir must exist before the emulator writes room thumbnails.
mkdir -p plugins logs camera/thumbnail

# ── 1. config.ini: generate ONCE, then it belongs to the user ──────────────
# NOTE: Arcturus 4.0.x switches to env-only config (ignoring this file) if a
# DB_HOSTNAME env var exists — which is why every variable below is ARC_-prefixed.
if [ ! -f config.ini ]; then
  echo "emulator: generating config.ini (first run — values from .env)"
  # Write to .tmp and mv: later boots treat mere EXISTENCE of config.ini as
  # user ownership, so a failure mid-write (unset var, disk full, kill) must
  # not leave a truncated file that every restart then silently respects.
  cat > config.ini.tmp <<EOF
## Generated by the pixelrp emulator entrypoint on first run — edit freely,
## restarts never overwrite it. Delete it and restart to regenerate from .env.
db.hostname=${ARC_DB_HOST}
db.port=3306
db.database=${ARC_DB_NAME}
db.username=${ARC_DB_USER}
db.password=${ARC_DB_PASS}
db.params=
## HikariCP client pool. Server cap: max_connections in db/conf/my.cnf.
## After boot Arcturus resizes the pool to runtime.threads*2 (emulator_settings
## row, base DB default 8) — so these mostly matter during startup.
db.pool.minsize=5
db.pool.maxsize=25
## Raw-TCP game server (Flash-era). Nitro uses the websocket plugin instead;
## the plugin re-binds this server's pipeline on ws.nitro.port (2096, in DB).
game.host=0.0.0.0
game.port=3000
## RCON — how the CMS talks to the emulator. rcon.allowed matches IP strings
## EXACTLY (no CIDR), hence the static CMS IP from docker-compose.yml.
rcon.host=0.0.0.0
rcon.port=3001
rcon.allowed=${ARC_RCON_ALLOWED}
## RSA handshake for Flash clients — off for Nitro-only setups.
enc.enabled=false
EOF
  mv config.ini.tmp config.ini
else
  echo "emulator: existing config.ini found — leaving it untouched"
fi

# ── 2. The emulator jar (user-supplied, exactly one) ───────────────────────
shopt -s nullglob
jars=("$ART"/*.jar)
shopt -u nullglob
if [ ${#jars[@]} -eq 0 ]; then
  echo >&2 "emulator FATAL: no emulator jar in ./artifacts/arcturus/"
  echo >&2 "emulator FATAL: expected e.g. Habbo-4.0.1-beta-jar-with-dependencies.jar"
  echo >&2 "emulator FATAL: see artifacts/README.md for where to get it."
  exit 1
elif [ ${#jars[@]} -gt 1 ]; then
  echo >&2 "emulator FATAL: multiple jars in ./artifacts/arcturus/ — keep exactly one:"
  printf >&2 '  %s\n' "${jars[@]}"
  exit 1
fi
JAR="${jars[0]}"

# ── 3. NitroWebsockets plugin (required — Nitro cannot connect without it) ─
shopt -s nullglob
pjars=("$ART"/plugins/*.jar)
shopt -u nullglob
if [ ${#pjars[@]} -eq 0 ]; then
  echo >&2 "emulator FATAL: no plugin jars in ./artifacts/arcturus/plugins/"
  echo >&2 "emulator FATAL: the NitroWebsockets jar is REQUIRED for the Nitro client."
  echo >&2 "emulator FATAL: fetch it with:  make fetch-ws-plugin"
  exit 1
fi
# Reconcile, don't accumulate: jars removed/renamed in artifacts must also
# disappear from the persisted plugins dir, or Arcturus would load a stale
# copy alongside its replacement (duplicate plugin, second bind on ws 2096).
# Only *.jar files are pruned — plugin config subdirs/files are preserved.
rm -f plugins/*.jar
cp -f "${pjars[@]}" plugins/

# ── 4. Wait for MariaDB, then hand over to the emulator ────────────────────
echo "emulator: waiting for database at ${ARC_DB_HOST}:3306 ..."
until (echo > "/dev/tcp/${ARC_DB_HOST}/3306") 2>/dev/null; do sleep 2; done
echo "emulator: database reachable — starting $(basename "$JAR")"

# NOTE on Arcturus BETA builds: stock beta jars block forever on an interactive
# 'Press "ENTER" if you agree' gate (Emulator.java promptEnterKey) — feeding a
# newline through stdin does NOT reliably clear it (verified 2026-08). Use a
# jar built by scripts/build-emulator.sh, which patches the gate out; the
# stdin passthrough below keeps `docker attach` console commands usable.
# shellcheck disable=SC2086  # ARC_JAVA_OPTS is intentionally word-split
exec java ${ARC_JAVA_OPTS:--Xmx1g} -jar "$JAR" < <(cat)
